---
abstract: 'Processing PYX data or file and sort element attributes.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Perl6::Slurp: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: '1.02'
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-Sort
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  PYX::Parser: 0.03
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=PYX-Sort
  homepage: https://github.com/tupinek/PYX-Sort
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/PYX-Sort
version: '0.04'
